version: 2.1

openjdk13-docker-image: &openjdk13-docker-image
  working_directory: ~/repo
  docker:
  - image: openjdk:13-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  restore-gradle-cache:
    description: "Restore gradle cache"
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

  save-gradle-cache:
    description: "Save gradle cache"
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

jobs:
  test:
    <<: *openjdk13-docker-image
    steps:
    - checkout
    - restore-gradle-cache
    - run: ./gradlew clean classes testClasses
    - save-gradle-cache
    - run: ./gradlew check
    - store_test_results:
        path: build/test-results/test
    - store_artifacts:
        path: build/test-results/test
        when: always

workflows:
  version: 2
  workflow:
    jobs:
      - test
