Parameters:
  BucketName:
    Type: String
    Description: Bucket name of the datalake
  ProjectName:
    Type: String
    Description: Name of the project this datalake belongs to

Resources:
  DatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "Private"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      BucketName: !Ref BucketName
      Tags:
        - Key: Project
          Value: !Ref ProjectName
      VersioningConfiguration:
        Status: "Enabled"

Outputs:
  DatalakeARN:
    Description: ARN of the datalake
    Value: !GetAtt DatalakeBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
  DatalakeAddress:
    Description: DatalakeAddress
    Value: !Sub "s3://${BucketName}"
    Export:
      Name: !Sub '${AWS::StackName}-Address'
